// Writes public/_redirects: every old lit.smarterthanthat.com URL to its fiction.moriel.tech
// equivalent, in Netlify's format. Usage: npm run redirects (reads urls.json, from import.ts).
// The old domain must be a domain alias of the Netlify site for these rules to apply.
import { readFileSync, writeFileSync } from 'node:fs'
import { getTagSlug } from '../../src/lib/pieces.ts'

interface OldItem {
  id: string
  type: string
  status: string
  slug: string
  link: string
  /** WordPress's local date: "2015-10-25 14:29:40". */
  date: string
  categories: string[]
  tags: string[]
  tagSlugs: string[]
}

const OLD_HOSTS = ['https://lit.smarterthanthat.com', 'http://lit.smarterthanthat.com']
const NEW = 'https://fiction.moriel.tech'

// WordPress categories became types; "prose" held stories and flash, so it goes to the archive.
const CATEGORIES: Record<string, { page: string; feed: string }> = {
  poem: { page: '/poems/', feed: '/poems/rss.xml' },
  'flash-fiction': { page: '/flash/', feed: '/flash/rss.xml' },
  'short-story': { page: '/stories/', feed: '/stories/rss.xml' },
  prose: { page: '/archive/', feed: '/rss.xml' },
}

const PAGES: Record<string, string> = {
  'about-me': '/about/',
  contact: 'https://moriel.tech/contact',
}

const items: OldItem[] = JSON.parse(readFileSync(new URL('urls.json', import.meta.url), 'utf8'))
const published = items.filter((item) => item.status === 'publish')
const posts = published.filter((item) => item.type === 'post')

/** [old path, new path or URL]; old paths without trailing slashes (Netlify matches both). */
const rules: [string, string][] = []
const add = (from: string, to: string) => rules.push([from, to])

for (const post of posts) {
  const to = `/pieces/${post.slug}/`
  // WordPress answered at any of the post's categories, and at the bare slug.
  for (const category of new Set([new URL(post.link).pathname.split('/')[1], ...post.categories])) {
    add(`/${category}/${post.slug}`, to)
    // Comment feeds, attachment pages, and anything else under the post.
    add(`/${category}/${post.slug}/*`, to)
  }
  add(`/${post.slug}`, to)
}

for (const page of published.filter((item) => item.type === 'page')) {
  const to = PAGES[page.slug]
  if (!to) throw new Error(`No new home for the page "${page.slug}"`)
  add(`/${page.slug}`, to)
}

const usedCategories = new Set(posts.flatMap((post) => post.categories))
for (const [category, { page, feed }] of Object.entries(CATEGORIES)) {
  if (!usedCategories.has(category)) continue
  add(`/category/${category}/feed`, feed)
  add(`/category/${category}/feed/*`, feed)
  add(`/category/${category}`, page)
  add(`/category/${category}/*`, page)
}
const unmapped = [...usedCategories].filter((category) => !CATEGORIES[category])
if (unmapped.length) throw new Error(`No new home for the categories: ${unmapped.join(', ')}`)

const tags = new Map(posts.flatMap((post) => post.tagSlugs.map((slug, i) => [slug, post.tags[i]] as const)))
for (const [oldSlug, name] of [...tags].sort()) {
  add(`/tag/${oldSlug}/feed`, '/rss.xml')
  add(`/tag/${oldSlug}/feed/*`, '/rss.xml')
  add(`/tag/${oldSlug}`, `/tags/${getTagSlug(name)}/`)
  add(`/tag/${oldSlug}/*`, `/tags/${getTagSlug(name)}/`)
}

add('/feed', '/rss.xml')
add('/feed/*', '/rss.xml')
add('/comments/feed', '/rss.xml')
add('/comments/feed/*', '/rss.xml')

// Date archives (/2011/, /2011/04/) go to that year in the archive.
for (const year of [...new Set(posts.map((post) => post.date.slice(0, 4)))].sort()) {
  add(`/${year}`, `/archive/#year-${year}`)
  add(`/${year}/*`, `/archive/#year-${year}`)
}

add('/author/*', '/')
add('/page/*', '/')

const absolute = (to: string) => (to.startsWith('https://') ? to : `${NEW}${to}`)
const width = Math.max(...rules.map(([from]) => from.length)) + OLD_HOSTS[1].length + 2
const line = (from: string, to: string, status = '301!') => `${from.padEnd(width)} ${absolute(to).padEnd(60)} ${status}`

const output = [
  '# Old lit.smarterthanthat.com URLs → fiction.moriel.tech.',
  '# Generated by tools/wp-import/redirects.ts from the WordPress export; add new redirects by hand above it.',
  '# The old domain must be a domain alias of this Netlify site. Netlify matches with and without a',
  '# trailing slash; the first matching rule wins.',
  '',
  // ?p=123 and ?page_id=123 links go through /p/123 on the new site (Netlify matches query
  // parameters by name; the IDs are mapped by the path rules at the end).
  ...OLD_HOSTS.flatMap((host) => [line(`${host}/ p=:id`, `${NEW}/p/:id`), line(`${host}/ page_id=:id`, `${NEW}/p/:id`), line(`${host}/ feed=:feed`, '/rss.xml')]),
  '',
  ...OLD_HOSTS.flatMap((host) => [...rules.map(([from, to]) => line(`${host}${from}`, to)), '']),
  '# Everything else on the old domain (the home page, uploaded images) moves over as is: the',
  '# home page lands on the home page, and images, which weren\'t migrated, end on the 404 page.',
  ...OLD_HOSTS.map((host) => line(`${host}/*`, `${NEW}/:splat`)),
  '',
  '# Old ?p= and ?page_id= links, by WordPress ID.',
  ...published.map((item) => line(`/p/${item.id}`, item.type === 'post' ? `/pieces/${item.slug}/` : PAGES[item.slug])),
  '',
].join('\n')

writeFileSync(new URL('../../public/_redirects', import.meta.url), output)
console.log(`Wrote public/_redirects: ${rules.length * OLD_HOSTS.length + published.length} rules.`)
